name: Deploy DocC

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fwal/setup-swift@v1
        with:
          swift-version: "5.7.0"
      - name: build docc
        run: swift package --allow-writing-to-directory ./docs generate-documentation --target SlideKit --disable-indexing --output-path ./docs --transform-for-static-hosting --hosting-base-path SlideKit
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
